# Generated by Django 3.1.1 on 2020-09-17 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200916_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='is_completed',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='is_completed',
            new_name='completed',
        ),
    ]
